export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const FETCH_MENU_URL =
  "https://www.swiggy.com/dapi/menu/v4/full?lat=12.9351929&lng=77.62448069999999&menuId=";

//   "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=28.4743879&lng=77.50399039999999&restaurantId=362737&submitAction=ENTER" +
//     id
//   "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=12.9715987&lng=77.5945627&restaurantId=3241&submitAction=ENTER" +
//     id
// "https://www.swiggy.com/dapi/menu/v4/full?lat=12.9351929&lng=77.62448069999999&menuId=" +
//   id

// export const restrauntList = [
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "485952",
//       name: "Bansooriwala",
//       uuid: "26932860-c35d-4d50-a333-f248907bb0c4",
//       city: "10459",
//       area: "Greater Noida",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "hnqmhmnhwtissztl4r9d",
//       cuisines: [
//         "Sweets",
//         "Chaat",
//         "North Indian",
//         "Street Food",
//         "Desserts",
//         "Beverages",
//       ],
//       tags: [],
//       costForTwo: 25000,
//       costForTwoString: "₹250 FOR TWO",
//       deliveryTime: 27,
//       minDeliveryTime: 27,
//       maxDeliveryTime: 27,
//       slaString: "27 MINS",
//       lastMileTravel: 1.100000023841858,
//       slugs: {
//         restaurant: "bansooriwala-greater-noida-greater-noida",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "SHOP NO. G126, G127, G128, NEELKANTH PLAZA, COMMERCIAL BELT, SECTOR ALPHA 1, GREATER NOIDA, GautamBudh Nagar Tahsil-I, Gautam Buddha Nagar , Uttar Pradesh-201310",
//       locality: "Alpha 1",
//       parentId: 237871,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3400,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3400,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3400",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=6056975~p=1~eid=00000186-aaad-3c90-039c-daee00e40151",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.1 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "485952",
//         deliveryTime: 27,
//         minDeliveryTime: 27,
//         maxDeliveryTime: 27,
//         lastMileTravel: 1.100000023841858,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "3.9",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "303249",
//       name: "Theobroma",
//       uuid: "e9a5a9b5-9384-4cf6-ae00-3e2e007496c8",
//       city: "10459",
//       area: "Greater Noida",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "oj0xd8ih7gb2ci0vhb8j",
//       cuisines: ["Bakery", "Desserts"],
//       tags: [],
//       costForTwo: 80000,
//       costForTwoString: "₹800 FOR TWO",
//       deliveryTime: 24,
//       minDeliveryTime: 24,
//       maxDeliveryTime: 24,
//       slaString: "24 MINS",
//       lastMileTravel: 1.899999976158142,
//       slugs: {
//         restaurant: "the-obroma-greater-noida-greater-noida",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "LS-01, First Floor, KB Complex, Alpha-2, Greater Noida, Uttar Pradesh -201310",
//       locality: "Alpha 2",
//       parentId: 1040,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3000,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3000,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3000",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.8 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "303249",
//         deliveryTime: 24,
//         minDeliveryTime: 24,
//         maxDeliveryTime: 24,
//         lastMileTravel: 1.899999976158142,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.2",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "251755",
//       name: "BIRYANI N GRILL",
//       uuid: "cd8c363a-9b81-44d2-8af9-81bafcdaf38c",
//       city: "10459",
//       area: "Greater Noida",
//       totalRatingsString: "50+ ratings",
//       cloudinaryImageId: "eybuwyqd4bvtjivshhmw",
//       cuisines: ["Indian", "Biryani"],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 14,
//       minDeliveryTime: 14,
//       maxDeliveryTime: 14,
//       slaString: "14 MINS",
//       lastMileTravel: 0.699999988079071,
//       slugs: {
//         restaurant: "biryani-n-grill-greater-noida-greater-noida",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address: "SHOP NO-G-30,BETA PLAZA,SECTOR BETA-1,GREATER NOIDA-201310",
//       locality: "Beta 1",
//       parentId: 46877,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "30% off",
//         shortDescriptionList: [
//           {
//             meta: "30% off on all orders",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "30% off on all orders",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "30% OFF",
//         shortDescriptionList: [
//           {
//             meta: "",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "30% off on all orders",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.6 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "251755",
//         deliveryTime: 14,
//         minDeliveryTime: 14,
//         maxDeliveryTime: 14,
//         lastMileTravel: 0.699999988079071,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.0",
//       totalRatings: 50,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "536944",
//       name: "Aggarwal Bikaneri Sweets And Restaurant",
//       uuid: "1c466288-d66e-4b4b-8b9c-adff98944e67",
//       city: "10459",
//       area: "Greater Noida",
//       totalRatingsString: "20+ ratings",
//       cloudinaryImageId: "txytqpugbzcatp1vswxc",
//       cuisines: ["Sweets", "Snacks"],
//       tags: [],
//       costForTwo: 9900,
//       costForTwoString: "₹99 FOR TWO",
//       deliveryTime: 14,
//       minDeliveryTime: 14,
//       maxDeliveryTime: 14,
//       slaString: "14 MINS",
//       lastMileTravel: 0.699999988079071,
//       slugs: {
//         restaurant:
//           "aggarwal-bikaneri-sweets-and-restaurant-greater-noida-greater-noida",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "shop no 25, second floor, beta plaza, beta 1, greater noida, BITA-1, GautamBudh Nagar Tahsil-I, Gautam Buddha Nagar , Uttar Pradesh - 201306",
//       locality: "Beta 1",
//       parentId: 323297,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.6 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "536944",
//         deliveryTime: 14,
//         minDeliveryTime: 14,
//         maxDeliveryTime: 14,
//         lastMileTravel: 0.699999988079071,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.2",
//       totalRatings: 20,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "105798",
//       name: "The Royal Kitchen",
//       uuid: "c6329d17-235f-4a2f-85e4-375f9e8fe63d",
//       city: "10459",
//       area: "Greater Noida",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "aulvgqbysmkfvrqypuvu",
//       cuisines: ["North Indian", "Chinese", "Mughlai"],
//       tags: [],
//       costForTwo: 35000,
//       costForTwoString: "₹350 FOR TWO",
//       deliveryTime: 24,
//       minDeliveryTime: 24,
//       maxDeliveryTime: 24,
//       slaString: "24 MINS",
//       lastMileTravel: 0.20000000298023224,
//       slugs: {
//         restaurant: "the-royal-kitchen-knowledge-park-1-greater-noida",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address: "shop no 19 , op plaza ,near kailesh hospital ,knowledge park 1",
//       locality: "Knowledge Park",
//       parentId: 2702,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=6103049~p=4~eid=00000186-b7d8-5329-15e2-969e0081046f",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.2 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "105798",
//         deliveryTime: 24,
//         minDeliveryTime: 24,
//         maxDeliveryTime: 24,
//         lastMileTravel: 0.20000000298023224,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.0",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "558537",
//       name: "Burger Hub",
//       uuid: "a8197fa5-e3dc-427f-9835-d888d6090f29",
//       city: "10459",
//       area: "Greater Noida",
//       totalRatingsString: "Too Few Ratings",
//       cloudinaryImageId: "o7jhkazk49q0ouxunuoy",
//       cuisines: ["American", "Fast Food", "Beverages"],
//       tags: [],
//       costForTwo: 9900,
//       costForTwoString: "₹99 FOR TWO",
//       deliveryTime: 15,
//       minDeliveryTime: 15,
//       maxDeliveryTime: 15,
//       slaString: "15 MINS",
//       lastMileTravel: 0.699999988079071,
//       slugs: {
//         restaurant: "burger-hub-greater-noida-greater-noida-2",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "SHOP NO G-20 BETA PLAZA, BETA -1 GREATER NOIDA, GautamBudh Nagar Tahsil-I, Gautam Buddha Nagar , Uttar Pradesh, 201310",
//       locality: "Beta 1",
//       parentId: 21787,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.6 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "558537",
//         deliveryTime: 15,
//         minDeliveryTime: 15,
//         maxDeliveryTime: 15,
//         lastMileTravel: 0.699999988079071,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "--",
//       totalRatings: 0,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "362737",
//       name: "NIC Ice Creams",
//       uuid: "f751b464-cffa-46cb-9b0e-85356ab45e4e",
//       city: "10459",
//       area: "Greater Noida",
//       totalRatingsString: "50+ ratings",
//       cloudinaryImageId: "91d6dda411b108965541c16ac1cfe2bc",
//       cuisines: ["Ice Cream", "Desserts"],
//       tags: [],
//       costForTwo: 12000,
//       costForTwoString: "₹120 FOR TWO",
//       deliveryTime: 15,
//       minDeliveryTime: 15,
//       maxDeliveryTime: 15,
//       slaString: "15 MINS",
//       lastMileTravel: 1.899999976158142,
//       slugs: {
//         restaurant: "nic-natural-ice-creams-alfa-2-greater-noida",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "SHOP NO G-25(GROUND FLOOR), SAT, SHYAM 2 SHOPPINGCOMPLEX CS-05, SECTOR ALFA II, GREATER NOIDA,UP-201308",
//       locality: "Alpha 2",
//       parentId: 6249,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "50% off",
//         shortDescriptionList: [
//           {
//             meta: "50% off | Use SPECIALS",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 on select items | Use code SPECIALS",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "50% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use SPECIALS",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "50% off up to ₹100 on select items | Use code SPECIALS",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 2700,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 2700,
//         message: "",
//         title: "Delivery Charge",
//         amount: "2700",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.8 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "362737",
//         deliveryTime: 15,
//         minDeliveryTime: 15,
//         maxDeliveryTime: 15,
//         lastMileTravel: 1.899999976158142,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.5",
//       totalRatings: 50,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "246633",
//       name: "Curry Mahal",
//       uuid: "41aea99a-abcc-4727-abb7-f207d55bd166",
//       city: "10459",
//       area: "Greater Noida",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "hvpsuwy6v0hemyicdwwx",
//       cuisines: ["Indian", "North Indian", "Biryani", "Thalis"],
//       tags: [],
//       costForTwo: 35000,
//       costForTwoString: "₹350 FOR TWO",
//       deliveryTime: 21,
//       minDeliveryTime: 21,
//       maxDeliveryTime: 21,
//       slaString: "21 MINS",
//       lastMileTravel: 1.899999976158142,
//       slugs: {
//         restaurant: "salt-&-pepper-village-greater-noida-greater-noida",
//         city: "noida-1",
//       },
//       cityState: "10459",
//       address:
//         "TF-18, Third Floor, Plot no - LS-1, KB Complex, Sector Alpha 2, Greater Noida, G.B Nagar , Up 201308, ALPHA-2, GautamBudh Nagar Tahsil-I, Gautam Buddha Nagar , Uttar Pradesh",
//       locality: "Alpha 2",
//       parentId: 13353,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5995115~p=7~eid=00000186-b7d8-5329-15e2-969f0081075c",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.8 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "246633",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         lastMileTravel: 1.899999976158142,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "3.8",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
// ];
